### ISSUE TITLE
Error trying to plot an axis.

### ISSUE THREAD

**Issue by AndreaDiPietro92** [fsmMLK/inkscapeCartesianPlotData2D#4]
When I trying to plot axis in inkscape i get these errors. 

Inkscape 1.1.1 (3bf5ae0d25, 2021-09-20)

```
Traceback (most recent call last):
  File "/home/user/.config/inkscape/extensions/textext/base.py", line 558, in tex_to_pdf
    exec_command([tex_command, self.tmp('tex')] + self.LATEX_OPTIONS)
  File "/home/user/.config/inkscape/extensions/textext/utility.py", line 240, in exec_command
    raise TexTextCommandFailed(message="Command %s failed (code %d)" % (' '.join(cmd), p.returncode),
textext.errors.TexTextCommandFailed: Command /usr/bin/pdflatex tmp.tex -interaction=nonstopmode -halt-on-error failed (code 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/.config/inkscape/extensions/cartesianAxes2D/cartesianAxes2D.py", line 89, in <module>
    axis.run()
  File "/usr/share/inkscape/extensions/inkex/base.py", line 131, in run
    self.save_raw(self.effect())
  File "/home/user/.config/inkscape/extensions/cartesianAxes2D/cartesianAxes2D.py", line 81, in effect
    inkPlot.axis.cartesian(self, root_layer, Xlimits, Ylimits, position, xLabel=so.xLabel, yLabel=so.yLabel, xlog10scale=so.xLog10scale,
  File "/home/user/.config/inkscape/extensions/inkscapeMadeEasy/inkscapeMadeEasy_Plot.py", line 554, in cartesian
    inkDraw.text.latex(ExtensionBaseObj, GroupAxis, xLabel,
  File "/home/user/.config/inkscape/extensions/inkscapeMadeEasy/inkscapeMadeEasy_Draw.py", line 1291, in latex
    tex.run(
  File "/usr/share/inkscape/extensions/inkex/base.py", line 131, in run
    self.save_raw(self.effect())
  File "/home/user/.config/inkscape/extensions/textext/base.py", line 315, in effect
    self.do_convert(new_text,
  File "/home/user/.config/inkscape/extensions/textext/base.py", line 388, in do_convert
    converter.tex_to_pdf(tex_executable, text, preamble_file)
  File "/home/user/.config/inkscape/extensions/textext/base.py", line 562, in tex_to_pdf
    raise TexTextConversionError(parsed_log, error.return_code, error.stdout, error.stderr)
textext.errors.TexTextConversionError: ! Package keyvalue Error: Unknown option 'per' for package siunitx.


For immediate help type H <return>.
```

**Comment by AndreaDiPietro92** [comment]
I have found the solution. Modify the file `basicLatexPackages.tex ` in `~/.config/inkscape/extensions/inkscapeMadeEasy` adding
```
\usepackage[]{siunitx}
\sisetup{per-mode=symbol}
```
